// src/components/Introduction.vue
<template>
  <div class="flex flex-col items-center mt-3 md:flex-row">
    <g-image
      alt="profile image"
      class="profile-image rounded-full shadow-lg md:shadow-none md:w-1/3 md:mr-4"
      src="~/assets/max_profile.png"
      width="500"
    />
    <div class="md:w-2/3">
      <h2>I'm Max!</h2>
      <p>
        Hello and welcome to my website! I'll be showing off a lot of stuff here, but I'm mostly a software developer.
        This website is a place to discover a little bit more about me. If you want to see some of my work, click
        <g-link to="/portfolio" class="link">here</g-link>. I'm attempting to start a blog which you can find
        <g-link to="/blog" class="link">here</g-link>. I'll constantly be updating this website so please come back to see the new features.
        Hopefully you enjoy what I've done here.
      </p>
    </div>
  </div>
</template>

<script>
export default {};
</script>

// app/components/Introduction.tsx
import Image from 'next/image';
import Link from 'next/link';

export default function Introduction() {
  return (
    <div className="flex flex-col items-center mt-3 md:flex-row mb-3" id="introduction">
      <div className="w-64 h-64 md:w-1/3 md:mr-4 mb-4 md:mb-0">
        <Image
          alt="profile image"
          src="/max_profile.png"
          width={500}
          height={500}
          className="rounded-full shadow-lg md:shadow-none w-full h-full object-cover"
          priority
        />
      </div>
      <div className="md:w-2/3 text-center md:text-left">
        <h2 className="text-2xl font-bold mb-4">I'm Max!</h2>
        <p className="text-base leading-relaxed">
          Hello and welcome to my website! I'll be showing off a lot of stuff here, but I'm mostly a software developer.
          This website is a place to discover a little bit more about me. If you want to see some of my work, click{' '}
          <Link href="/portfolio" className="link">
            here
          </Link>
          . I'm attempting to start a blog which you can find{' '}
          <Link href="/blog" className="link">
            here
          </Link>
          . I'll constantly be updating this website so please come back to see the new features.
          Hopefully you enjoy what I've done here.
        </p>
      </div>
    </div>
  );
}
