// src/pages/Blog.vue
<template>
  <Layout>
    <div class="flex flex-col">
      <g-link v-for="edge in $page.blogPosts.edges" :key="edge.node.id" :to="edge.node.path">
        <div class="shadow p-3 hover:shadow-lg">
          <div class>
            <div class="font-bold text-xl">{{edge.node.title}}</div>
            <p class="text-gray-700 text-base">{{edge.node.excerpt}}</p>
            <p class="text-gray-400 text-sm">{{edge.node.date}}</p>
          </div>
          <div class="pt-3">
            <g-link v-for="tag in edge.node.tags" :key="tag.id" :to="tag.path">
              <span
                class="inline-block bg-gray-100 px-3 py-1 text-sm font-semibold text-gray-500 mr-2 hover:bg-gray-200"
              >#{{tag.id}}</span>
            </g-link>
          </div>
        </div>
      </g-link>
    </div>
  </Layout>
</template>

<script>
export default {
  data() {
    return {
      tags: [
        { text: "vue", path: "/" },
        { text: "javascript", path: "/" },
        { text: "self help", path: "/" }
      ]
    };
  },
  metaInfo: {
    title: "Max's Blog"
  }
};
</script>

<page-query>
query BlogPosts {
  blogPosts: allBlogPost {
    edges {
      node {
        id
        title
        author
        excerpt
        date(format: "MMMM DD, YYYY")
        path
        tags {
          id
          path
        }
      }
    }
  }
}
</page-query>

// app/blog/page.tsx
import Layout from '../components/Layout';
import Link from 'next/link';
import { getSortedBlogData } from '../../lib/blog';

export default function Blog() {
  const blogPosts = getSortedBlogData();

  return (
    <Layout>
      <div>
        {/* Blog Posts */}
        <div className="flex flex-col space-y-4">
          {blogPosts.map((post) => (
            <Link key={post.slug} href={`/blog/${post.slug}`}>
              <div className="shadow p-3 hover:shadow-lg transition-shadow cursor-pointer">
                <div>
                  <h3 className="text-xl font-semibold">{post.title}</h3>
                  <p className="text-gray-700 text-base">{post.excerpt}</p>
                  <p className="text-gray-400 text-sm">{post.date}</p>
                </div>
                <div className="pt-3">
                  <div className="flex flex-wrap gap-2">
                    {post.tags.map((tag: string) => (
                      <span
                        key={tag}
                        className="inline-block bg-gray-100 px-3 py-1 text-sm font-semibold text-gray-500"
                      >
                        #{tag}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            </Link>
          ))}
        </div>
      </div>
    </Layout>
  );
}
