// app/components/MoreButton.tsx
'use client';

import { useState } from 'react';
import Link from 'next/link';

interface NavItem {
  text: string;
  path: string;
  icon: string;
  overflow?: boolean;
}

interface MoreButtonProps {
  items: NavItem[];
}

export default function MoreButton({ items }: MoreButtonProps) {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className="relative">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center space-x-1"
      >
        <i className="fa fa-bars"></i>
        <span>More</span>
      </button>
      
      {isOpen && (
        <>
          {/* Backdrop */}
          <div
            className="fixed inset-0 z-10"
            onClick={() => setIsOpen(false)}
          />
          
          {/* Dropdown menu */}
          <div className="absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg z-20 border">
            <div className="py-1">
              {items.map((item) => (
                <Link
                  key={item.text}
                  href={item.path}
                  className="flex items-center px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                  onClick={() => setIsOpen(false)}
                >
                  <i className={`fa ${item.icon} mr-2`}></i>
                  {item.text}
                </Link>
              ))}
            </div>
          </div>
        </>
      )}
    </div>
  );
}

// src/components/MoreButton.vue
<template>
  <div class="relative">
    <div @click="toggleShowMenu">
      <i class="fa fa-ellipsis-v"></i>
      <span>{{text}}</span>
    </div>
    <div id="popup-menu" v-if="showMenu" class="shadow">
      <g-link v-for="item in items" :key="item.text" :to="item.path">
        <div class="p-3 hover:bg-gray-300" @click="toggleShowMenu"><i class="fa" :class="item.icon"></i> {{item.text}}</div>
      </g-link>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    items: Array
  },
  data() {
    return {
      showMenu: false
    };
  },
  methods: {
    toggleShowMenu() {
      this.showMenu = !this.showMenu;
    }
  },
  computed: {
    text() {
      return this.showMenu ? "Less" : "More";
    }
  }
};
</script>

<style scoped>
#popup-menu {
  @apply absolute bg-white z-10;
  min-width: 200px;
  top: 40px;
  right: -20px;
}
</style>
